# Generated by Django 4.0.2 on 2022-02-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_actions', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bulk_discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rooms', models.IntegerField()),
                ('bulk_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type_desc', models.CharField(max_length=240)),
                ('allowed_actions', models.ManyToManyField(to='Lodge.Actions')),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_desc', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Seasonal_discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('seasonal_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=240)),
                ('username', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('sleeps', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('cot', models.IntegerField()),
                ('disabled_access', models.IntegerField()),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.room_type')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('booking_room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.booking_rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(auto_now_add=True)),
                ('booking_room_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.booking_rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.DateTimeField()),
                ('last_date', models.DateTimeField()),
                ('booked_date', models.DateTimeField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.customers')),
            ],
        ),
        migrations.AddField(
            model_name='booking_rooms',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.bookings'),
        ),
        migrations.AddField(
            model_name='booking_rooms',
            name='room_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Lodge.rooms'),
        ),
    ]
