# Generated by Django 4.0.2 on 2022-02-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_rooms',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.rooms'),
        ),
    ]
