# Generated by Django 4.0.1 on 2022-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0013_rename_checked_in_guests_checked_in_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.CharField(max_length=20)),
            ],
        ),
    ]
