# Generated by Django 4.0.1 on 2022-02-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0014_checkin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkins',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='Lodge.Checkin_date'),
        ),
    ]
