# Generated by Django 4.0.1 on 2022-02-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0015_booking_checkins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin_date',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
