# Generated by Django 4.0.1 on 2022-02-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0016_alter_checkin_date_checkin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checked_in_guest',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='checkin_date',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Lodge.customer'),
        ),
    ]
