# Generated by Django 4.0.1 on 2022-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0017_remove_checked_in_guest_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkins',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='checkin',
            field=models.ManyToManyField(blank=True, related_name='customers', to='Lodge.Checkin'),
        ),
        migrations.DeleteModel(
            name='Checkin_date',
        ),
    ]
